### ISSUE TITLE
在沉浸翻译里500: fetchError

### ISSUE THREAD

**Issue by bailitingqin** [cliouo/FreeGPT35-Vercel#16]
500: fetchError

是按照在沉浸式翻译中使用接口地址：https://freechatgpt35-XXXX-projects.vercel.app/v1/chat/completions这种格式设定的呀？

POST

/v1/chat/completions

xxx
TypeError: Cannot read properties of undefined (reading 'startsWith')
    at new n (/var/task/node_modules/@upstash/redis/nodejs.js:1:834)
    at new VercelKV (file:///var/task/node_modules/@vercel/kv/dist/index.js:5:16)
    at createClient (file:///var/task/node_modules/@vercel/kv/dist/index.js:61:10)
    at handleChatCompletion (file:///var/task/api/index.js:138:13)
    at Server.<anonymous> (/var/task/___vc/__launcher/helpers-N7IX3CRI.js:1:7894)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Server.<anonymous> (/var/task/___vc/__launcher/bridge-server-BGIDXK2J.js:1:9443)

[POST] /v1/chat/completions status=500

Status已经是ready了，https://freechatgpt35-XXXX-projects.vercel.app/    也是能打开的，但是设置到沉浸式翻译中就不好用了。
请问这是什么问题啊？

**Comment by cliouo** [comment]
数据库没连上

**Comment by cliouo** [comment]
如果用Vercel kv数据库 检查是否项目和数据库是否连上了，如果用upstash，检查环境变量配置
以上配置好之后要Redeploy重新部署一下

**Comment by bailitingqin** [comment]
我是一键部署的，只改了AUTH_TOKEN变量设置了key。
请问哪里有相对完善的指导文档么？我再仔细研究一下，谢谢。

**Comment by bailitingqin** [comment]
我用了kv数据库，虽然还是500: fetchError，但log变成这样了
TypeError: Cannot destructure property 'sessionArr' of '(intermediate value)' as it is null.
    at handleChatCompletion (file:///var/task/api/index.js:144:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Server.<anonymous> (/var/task/___vc/__launcher/helpers-N7IX3CRI.js:1:7888)
    at async Server.<anonymous> (/var/task/___vc/__launcher/bridge-server-BGIDXK2J.js:1:9443)

cron-job是必须的么？
除了可选域名和第八步cron-job我都做了。

谢谢

**Comment by cliouo** [comment]
是的，main分支必须要定时任务是为了定时刷新oai的token，不然vercel没办法自己更新

**Comment by bailitingqin** [comment]
谢谢
